name: Deploy PantrySync

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure environment
        run: |
          echo "EXPO_PUBLIC_DEPLOYED_AT=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "EXPO_PUBLIC_API_URL=https://api.pantrysync.app" >> $GITHUB_ENV
          echo "EXPO_PUBLIC_API_KEY=${{ secrets.EXPO_PUBLIC_API_KEY }}" >> $GITHUB_ENV

      - name: Build for web
        run: npm run build:web
        env:
          EXPO_PUBLIC_DEPLOYED_AT: ${{ env.EXPO_PUBLIC_DEPLOYED_AT }}
          EXPO_PUBLIC_API_URL: ${{ env.EXPO_PUBLIC_API_URL }}
          EXPO_PUBLIC_API_KEY: ${{ env.EXPO_PUBLIC_API_KEY }}

      - name: Deploy to Firebase Hosting
        if: github.ref == 'refs/heads/main'
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}

  build-mobile:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Configure environment
        run: |
          echo "EXPO_PUBLIC_DEPLOYED_AT=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Build app for EAS
        run: |
          npx eas build --platform all --non-interactive --wait
        env:
          EXPO_PUBLIC_DEPLOYED_AT: ${{ env.EXPO_PUBLIC_DEPLOYED_AT }}
          EXPO_PUBLIC_API_URL: https://api.pantrysync.app
          EXPO_PUBLIC_API_KEY: ${{ secrets.EXPO_PUBLIC_API_KEY }}

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate

      - name: Validate environment variables
        run: |
          echo "Validating required environment variables..."
          if [ -z "${{ secrets.FIREBASE_TOKEN }}" ]; then
            echo "Error: FIREBASE_TOKEN secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "Error: EXPO_TOKEN secret is not set"  
            exit 1
          fi
          echo "Environment validation passed"